### ISSUE TITLE
Cannot be used in version 1.19purpur

### ISSUE THREAD

**Issue by SueFox** [OfficialRell/ExtractableEnchantments#1]
[latest.log](https://github.com/user-attachments/files/16182613/latest.log)
but i can use it in version 1.20.6purpur
（I used a translator, please understand if there are any inaccuracies in the translation）

**Comment by OfficialRell** [comment]
That is an API issue. I will fix that in few days.

**Comment by OfficialRell** [comment]
Plugin has been updated with this issue fixed.
