### ISSUE TITLE
Applying 64 dust to 64 extractors is the same as applying 1 dust to 1 extractors

### ISSUE THREAD

**Issue by SueFox** [OfficialRell/ExtractableEnchantments#3]
https://github.com/user-attachments/assets/be733a2d-745b-4910-b705-5f058051263e

**Comment by OfficialRell** [comment]
Dust shouldn't be stacked, it should just be a single item and players should only have dust as a single item.
I will have to make that you can only apply dust to a single extractor.

**Comment by OfficialRell** [comment]
Dust will now automatically fix its percentage depending on the dust item amount.
