### ISSUE TITLE
 several dust reaching the upper limit chance cannot be stacked sometimes(they are like Spider Solitaire)

### ISSUE THREAD

**Issue by SueFox** [OfficialRell/ExtractableEnchantments#4]
![4fbe4cbbe289a846d8900004b7009c27](https://github.com/user-attachments/assets/db644549-34cc-4df1-a816-2282f7d7a9ea)

https://github.com/user-attachments/assets/ce67115e-8b32-4804-ab77-6e2540864e87

**Comment by OfficialRell** [comment]
Dust items should be stacked, they should be as a single item.

**Comment by OfficialRell** [comment]
Multiple dust items have been fixed, they will always turn into single item.
