### ISSUE TITLE
[Suggestion] Support for Enchantment+

### ISSUE THREAD

**Issue by EarthKone** [OfficialRell/ExtractableEnchantments#5]
Great plugin! Exactly what I was looking for. Only thing I wish it had was support for enchants from Enchantment+ by Wyvernity.

Planet Minecraft link: [https://www.planetminecraft.com/data-pack/enchantment-1-16/](https://www.planetminecraft.com/data-pack/enchantment-1-16/)

**Comment by OfficialRell** [comment]
Thanks! I am looking at it and it is a data pack, and I haven't worked with any data packs, but I'll try to add support for its enchantments.

**Comment by OfficialRell** [comment]
I have updated the plugin, it should now support Enchantment+ echantments.

**Comment by EarthKone** [comment]
Version 11.4 seems to have an issue when using the command, every time I try to use the /ee command it says "An internal error occurred while attempting to tab-complete this command. In Version 11.5, this issue is resolved, but I cannot extract any Enchantment+ enchantments.
